/*
 * generated by Xtext 2.33.0
 */
package componentesXtext.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class CbappScopeProvider extends AbstractCbappScopeProvider {

}
