/*
 * generated by Xtext 2.33.0
 */
package componentesXtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CbappRuntimeModule extends AbstractCbappRuntimeModule {
}
