/*
 * generated by Xtext 2.33.0
 */
package componentesXtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CbappStandaloneSetup extends CbappStandaloneSetupGenerated {

	public static void doSetup() {
		new CbappStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
