/*
 * generated by Xtext 2.33.0
 */
package componentesXtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCbappScopeProvider extends DelegatingScopeProvider {
}
