/*
 * generated by Xtext 2.33.0
 */
package componentesXtext.parser.antlr;

import com.google.inject.Inject;
import componentesXtext.parser.antlr.internal.InternalCbappParser;
import componentesXtext.services.CbappGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CbappParser extends AbstractAntlrParser {

	@Inject
	private CbappGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCbappParser createParser(XtextTokenStream stream) {
		return new InternalCbappParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "CBAPP";
	}

	public CbappGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CbappGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
